name: Basic CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bước 3: Build ứng dụng
      - name: Build application
        run: |
          npm install
          npm run build

      # Bước 4: Build và chạy Docker
      - name: Build and run Docker
        run: |
          docker build -t my-app .
          docker run -d -p 3000:3000 my-app
