name: Basic CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Build và chạy Docker cho backend
      - name: Build and run backend Docker
        run: |
          cd backend
          docker build -t my-backend .
          docker run -d -p 5002:5000 my-backend

      # Bước 4: Build và chạy Docker cho frontend
      - name: Build and run frontend Docker
        run: |
          cd frontend
          docker build -t my-frontend .
          docker run -d -p 3000:3000 my-frontend

      # Bước 5: Kiểm tra trạng thái của các container
      - name: Check container status
        run: |
          docker ps
